---
# Test Playbook

- hosts: vagrant-machines
  become: yes
  vars:
      package_name:
          - screen
          - vim
          - elinks

  tasks:
      - name: Ensure that the latest version of '{{ package_name }}' package is installed
        yum:
            name: "{{ package_name }}"
            state: latest
        when: ansible_os_family == "RedHat"

      - name: Ensure that the latest version of '{{ package_name }}' package is installed
        apt:
            name: "{{ package_name }}"
            state: latest
            update_cache: yes

        when: ansible_os_family == "Debian"

  handlers:
      - name: start "{{ package_name }}"
        service:
            name: "{{ package_name }}"
            enabled: yes
            state: started
