---
# tasks/delete-sites-enabled.yml    :   Delete the 'default' file in the 'sites-enabled' folder
#                                       This is usually needed only in Debian-based systems

- name: Remote 'default' file from 'sites-enabled' folder
  file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  when: ansible_os_family == "Debian"
  notify:
      - restart nginx service
