---
# install.yml   :   Install Nginx package

- name: Install Nginx package on Debian-based systems
  apt:
      name: nginx
      state: latest
      update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Nginx package on RedHat-based systems
  yum:
      name: nginx
      state: latest
      update_cache: yes
  when: ansible_os_family == "RedHat"
